[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
